### ISSUE TITLE
Failure to build raygun and example (Windows Visual Studio 2019)

### ISSUE THREAD

**Issue by Austin-Routt** [W4RH4WK/Raygun#9]
The windows build instructions work fine.
> C:\Raygun\Raygun-master>cmake.exe -G "Visual Studio 16 2019" -A x64 -B build
-- The CXX compiler identification is MSVC 19.23.28106.4
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.23.28105/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - not found
-- Found Threads: TRUE
-- Found Vulkan: C:/VulkanSDK/1.2.148.0/Lib/vulkan-1.lib
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Raygun/Raygun-master/build
>
However, when I attempt to build the the visual studio projects I get the following output:

> 1>------ Build started: Project: ZERO_CHECK, Configuration: Debug x64 ------
1>Checking Build System
2>------ Build started: Project: imgui, Configuration: Debug x64 ------
3>------ Build started: Project: fmt, Configuration: Debug x64 ------
2>Building Custom Rule C:/Raygun/Raygun-master/vendor/imgui/CMakeLists.txt
2>imgui.cpp
3>Building Custom Rule C:/Raygun/Raygun-master/vendor/fmt/CMakeLists.txt
3>format.cc
2>imgui_demo.cpp
2>imgui_draw.cpp
2>imgui_impl_glfw.cpp
2>imgui_impl_vulkan.cpp
2>imgui_widgets.cpp
3>posix.cc
2>imgui_stdlib.cpp
2>binary_to_compressed_c.cpp
2>Generating Code...
3>Generating Code...
2>imgui.vcxproj -> C:\Raygun\Raygun-master\build\vendor\imgui\Debug\imgui.lib
4>------ Build started: Project: imGuIZMO, Configuration: Debug x64 ------
3>fmt.vcxproj -> C:\Raygun\Raygun-master\build\vendor\fmt\Debug\fmt.lib
4>Building Custom Rule C:/Raygun/Raygun-master/vendor/imGuIZMO/CMakeLists.txt
4>imGuIZMO.cpp
4>imGuIZMO.vcxproj -> C:\Raygun\Raygun-master\build\vendor\imGuIZMO\Debug\imGuIZMO.lib
5>------ Build started: Project: raygun, Configuration: Debug x64 ------
5>Generating ../resources/shaders/closesthit.rchit.spv
5>C:/Raygun/Raygun-master/resources/shaders/closesthit.rchit : warning : C:/Raygun/Raygun-master/resources/shaders/raytracer_bindings.h:23: '#pragma once' : not implemented
5>1 warning generated.
5>Generating ../resources/shaders/fxaa.comp.spv
5>Generating ../resources/shaders/miss.rmiss.spv
5>C:/Raygun/Raygun-master/resources/shaders/miss.rmiss : warning : C:/Raygun/Raygun-master/resources/shaders/raytracer_bindings.h:23: '#pragma once' : not implemented
5>1 warning generated.
5>Generating ../resources/shaders/postprocess.comp.spv
5>Generating ../resources/shaders/raygen.rgen.spv
5>C:/Raygun/Raygun-master/resources/shaders/raygen.rgen : warning : C:/Raygun/Raygun-master/resources/shaders/raytracer_bindings.h:23: '#pragma once' : not implemented
5>1 warning generated.
5>Generating ../resources/shaders/rough_blur_h.comp.spv
5>Generating ../resources/shaders/rough_blur_v.comp.spv
5>Generating ../resources/shaders/rough_prepare.comp.spv
5>Generating ../resources/shaders/shadowMiss.rmiss.spv
5>Building Custom Rule C:/Raygun/Raygun-master/CMakeLists.txt
5>cmake_pch.cxx
5>audio_source.cpp
5>audio_system.cpp
5>sound.cpp
5>camera.cpp
5>compute_system.cpp
5>config.cpp
5>entity.cpp
5>descriptor_set.cpp
5>gpu_buffer.cpp
5>gpu_material.cpp
5>gpu_queue.cpp
5>gpu_utils.cpp
5>image.cpp
5>shader.cpp
5>uniform_buffer.cpp
5>input_system.cpp
5>logging.cpp
5>material.cpp
5>physics_sim_callback.cpp
5>physics_system.cpp
5>profiler.cpp
5>raygun.cpp
5>acceleration_structure.cpp
5>fade.cpp
5>imgui_renderer.cpp
5>mesh.cpp
5>model.cpp
5>raytracer.cpp
5>C:\Raygun\Raygun-master\raygun/utils/vulkan_types.def(31,1): error C2039: 'ObjectTableNVX': is not a member of 'vk' (compiling source file C:\Raygun\Raygun-master\raygun\render\acceleration_structure.cpp)
5>C:\VulkanSDK\1.2.148.0\Include\vulkan/vulkan.hpp(13486): message : see declaration of 'vk' (compiling source file C:\Raygun\Raygun-master\raygun\render\acceleration_structure.cpp)
5>C:\Raygun\Raygun-master\raygun/utils/vulkan_type_utils.hpp(46): message : see reference to function template instantiation 'vk::DebugReportObjectTypeEXT raygun::vulkan::getDebugReportObjectTypeEXT<T>(void)' being compiled
5>C:\Raygun\Raygun-master\raygun/utils/vulkan_type_utils.hpp(46): message :         with
5>C:\Raygun\Raygun-master\raygun/utils/vulkan_type_utils.hpp(46): message :         [
5>C:\Raygun\Raygun-master\raygun/utils/vulkan_type_utils.hpp(46): message :             T=vk::AccelerationStructureKHR
5>C:\Raygun\Raygun-master\raygun/utils/vulkan_type_utils.hpp(46): message :         ] (compiling source file C:\Raygun\Raygun-master\raygun\render\acceleration_structure.cpp)
5>C:\Raygun\Raygun-master\raygun/utils/vulkan_type_utils.hpp(50): message : see reference to class template instantiation 'raygun::vulkan::is_vulkan_type<T>' being compiled
5>C:\Raygun\Raygun-master\raygun/utils/vulkan_type_utils.hpp(50): message :         with
5>C:\Raygun\Raygun-master\raygun/utils/vulkan_type_utils.hpp(50): message :         [
5>C:\Raygun\Raygun-master\raygun/utils/vulkan_type_utils.hpp(50): message :             T=vk::AccelerationStructureKHR
5>C:\Raygun\Raygun-master\raygun/utils/vulkan_type_utils.hpp(50): message :         ] (compiling source file C:\Raygun\Raygun-master\raygun\render\acceleration_structure.cpp)
5>C:\Raygun\Raygun-master\raygun/vulkan_context.hpp(71): message : see reference to variable template 'const bool is_vulkan_type_v<vk::AccelerationStructureKHR>' being compiled (compiling source file C:\Raygun\Raygun-master\raygun\render\acceleration_structure.cpp)
5>C:\Raygun\Raygun-master\raygun\render\acceleration_structure.cpp(158): message : see reference to function template instantiation 'void raygun::VulkanContext::setObjectName<Type>(const T &,raygun::string_view)' being compiled
5>C:\Raygun\Raygun-master\raygun\render\acceleration_structure.cpp(158): message :         with
5>C:\Raygun\Raygun-master\raygun\render\acceleration_structure.cpp(158): message :         [
5>C:\Raygun\Raygun-master\raygun\render\acceleration_structure.cpp(158): message :             Type=vk::AccelerationStructureKHR,
5>C:\Raygun\Raygun-master\raygun\render\acceleration_structure.cpp(158): message :             T=vk::AccelerationStructureKHR
5>C:\Raygun\Raygun-master\raygun\render\acceleration_structure.cpp(158): message :         ]
5>C:\Raygun\Raygun-master\vendor\glm\include\glm\ext\matrix_transform.inl(6): message : see reference to class template instantiation 'glm::detail::init_gentype<genType,glm::detail::GENTYPE_MAT>' being compiled
5>C:\Raygun\Raygun-master\vendor\glm\include\glm\ext\matrix_transform.inl(6): message :         with
5>C:\Raygun\Raygun-master\vendor\glm\include\glm\ext\matrix_transform.inl(6): message :         [
5>C:\Raygun\Raygun-master\vendor\glm\include\glm\ext\matrix_transform.inl(6): message :             genType=raygun::mat4
5>C:\Raygun\Raygun-master\vendor\glm\include\glm\ext\matrix_transform.inl(6): message :         ] (compiling source file C:\Raygun\Raygun-master\raygun\render\acceleration_structure.cpp)
5>C:\Raygun\Raygun-master\raygun/transform.hpp(40): message : see reference to function template instantiation 'genType glm::identity<raygun::mat4>(void)' being compiled
5>C:\Raygun\Raygun-master\raygun/transform.hpp(40): message :         with
5>C:\Raygun\Raygun-master\raygun/transform.hpp(40): message :         [
5>C:\Raygun\Raygun-master\raygun/transform.hpp(40): message :             genType=raygun::mat4
5>C:\Raygun\Raygun-master\raygun/transform.hpp(40): message :         ] (compiling source file C:\Raygun\Raygun-master\raygun\render\acceleration_structure.cpp)
5>C:\Raygun\Raygun-master\raygun/utils/vulkan_type_utils.hpp(32,1): error C2065: 'ObjectTableNVX': undeclared identifier (compiling source file C:\Raygun\Raygun-master\raygun\render\acceleration_structure.cpp)
5>C:\Raygun\Raygun-master\raygun/utils/vulkan_types.def(31,1): error C2923: 'std::is_same_v': 'ObjectTableNVX' is not a valid template type argument for parameter '<unnamed-symbol>' (compiling source file C:\Raygun\Raygun-master\raygun\render\acceleration_structure.cpp)
5>C:\Raygun\Raygun-master\raygun/utils/vulkan_type_utils.hpp(32,1): error C2059: syntax error: ')' (compiling source file C:\Raygun\Raygun-master\raygun\render\acceleration_structure.cpp)
5>C:\Raygun\Raygun-master\raygun/utils/vulkan_type_utils.hpp(32,1): error C2143: syntax error: missing ';' before '{' (compiling source file C:\Raygun\Raygun-master\raygun\render\acceleration_structure.cpp)
5>C:\Raygun\Raygun-master\raygun/utils/vulkan_types.def(31,1): error C2838: 'eObjectTableNVX': illegal qualified name in member declaration (compiling source file C:\Raygun\Raygun-master\raygun\render\acceleration_structure.cpp)
5>C:\Raygun\Raygun-master\raygun/utils/vulkan_type_utils.hpp(32,1): error C2065: 'eObjectTableNVX': undeclared identifier (compiling source file C:\Raygun\Raygun-master\raygun\render\acceleration_structure.cpp)
5>C:\Raygun\Raygun-master\raygun/utils/vulkan_type_utils.hpp(32,1): error C2181: illegal else without matching if (compiling source file C:\Raygun\Raygun-master\raygun\render\acceleration_structure.cpp)
5>C:\Raygun\Raygun-master\raygun/utils/vulkan_types.def(32,1): error C2039: 'IndirectCommandsLayoutNVX': is not a member of 'vk' (compiling source file C:\Raygun\Raygun-master\raygun\render\acceleration_structure.cpp)
5>C:\VulkanSDK\1.2.148.0\Include\vulkan/vulkan.hpp(13486): message : see declaration of 'vk' (compiling source file C:\Raygun\Raygun-master\raygun\render\acceleration_structure.cpp)
5>C:\Raygun\Raygun-master\raygun/utils/vulkan_type_utils.hpp(32,1): error C2065: 'IndirectCommandsLayoutNVX': undeclared identifier (compiling source file C:\Raygun\Raygun-master\raygun\render\acceleration_structure.cpp)
5>C:\Raygun\Raygun-master\raygun/utils/vulkan_types.def(32,1): error C2923: 'std::is_same_v': 'IndirectCommandsLayoutNVX' is not a valid template type argument for parameter '<unnamed-symbol>' (compiling source file C:\Raygun\Raygun-master\raygun\render\acceleration_structure.cpp)
5>C:\Raygun\Raygun-master\raygun/utils/vulkan_types.def(32,1): error C2838: 'eIndirectCommandsLayoutNVX': illegal qualified name in member declaration (compiling source file C:\Raygun\Raygun-master\raygun\render\acceleration_structure.cpp)
5>C:\Raygun\Raygun-master\raygun/utils/vulkan_type_utils.hpp(42,1): error C2059: syntax error: '}' (compiling source file C:\Raygun\Raygun-master\raygun\render\acceleration_structure.cpp)
5>C:\Raygun\Raygun-master\raygun/utils/vulkan_type_utils.hpp(42,1): error C2143: syntax error: missing ';' before '}' (compiling source file C:\Raygun\Raygun-master\raygun\render\acceleration_structure.cpp)
5>C:\Raygun\Raygun-master\raygun/utils/vulkan_type_utils.hpp(47,1): error C2143: syntax error: missing ';' before '}' (compiling source file C:\Raygun\Raygun-master\raygun\render\acceleration_structure.cpp)
5>C:\Raygun\Raygun-master\raygun/utils/vulkan_type_utils.hpp(47,1): error C2059: syntax error: '}' (compiling source file C:\Raygun\Raygun-master\raygun\render\acceleration_structure.cpp)
5>C:\Raygun\Raygun-master\raygun/utils/vulkan_type_utils.hpp(46,68): error C3615: constexpr function 'raygun::vulkan::getDebugReportObjectTypeEXT' cannot result in a constant expression (compiling source file C:\Raygun\Raygun-master\raygun\render\acceleration_structure.cpp)
5>C:\Raygun\Raygun-master\raygun/utils/vulkan_type_utils.hpp(46): message : failure was caused by control reaching the end of a constexpr function (compiling source file C:\Raygun\Raygun-master\raygun\render\acceleration_structure.cpp)
5>render_system.cpp
5>swapchain.cpp
5>resource_manager.cpp
5>scene.cpp
5>text.cpp
5>ui.cpp
5>vulkan_context.cpp
5>window.cpp
5>C:\Raygun\Raygun-master\raygun/utils/vulkan_type_utils.hpp(46,1): fatal error C1004: unexpected end-of-file found (compiling source file C:\Raygun\Raygun-master\raygun\render\acceleration_structure.cpp)
5>Done building project "raygun.vcxproj" -- FAILED.
6>------ Build started: Project: example, Configuration: Debug x64 ------
6>Building Custom Rule C:/Raygun/Raygun-master/example/CMakeLists.txt
6>cmake_pch.cxx
6>ball.cpp
6>example_scene.cpp
6>main.cpp
6>LINK : fatal error LNK1181: cannot open input file '..\Debug\raygun.lib'
6>Done building project "example.vcxproj" -- FAILED.
7>------ Build started: Project: ALL_BUILD, Configuration: Debug x64 ------
7>Building Custom Rule C:/Raygun/Raygun-master/CMakeLists.txt
========== Build: 5 succeeded, 2 failed, 0 up-to-date, 0 skipped ==========
>

Any idea what's going on here?

**Comment by W4RH4WK** [comment]
I suspect your Vulkan SDK version is too new: `Found Vulkan: C:/VulkanSDK/1.2.148.0`

The README states which verison of the Vulkan SDK should be used. Currently on master it's `1.2.131`.

The reason is that this project uses Vulkan's C++ API almost exclusively which isn't stable.

Please note that there is a dedicated branch for using the cross-vendor ray tracing stuff. It hasn't been merged yet since there is currently no official, stable driver supporting this *new* API.

**Comment by Austin-Routt** [comment]
Thank you!
